version: 2.1
orbs:
  docker: circleci/docker@0.5.19
  django-tools: pennlabs/django-tools@0.0.6
  helm-tools: pennlabs/helm-tools@0.1.11
  react-tools: pennlabs/react-tools@0.0.5

branch-filters: &branch-filters
  filters:
    branches:
      only:
        - master

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - django-tools/check:
          project-name: pennclubs
          project-location: backend
          python-version: "3.8"
      - react-tools/check:
          project-location: frontend
          image: pennlabs/frontend-test:latest
      - docker/publish:
          name: publish-clubs-backend
          requires:
            - django-tools/check
          path: backend
          cache_from: "pennlabs/penn-clubs-backend:latest"
          image: "pennlabs/penn-clubs-backend"
          tag: "${CIRCLE_SHA1},latest"
          context: docker-publish
          <<: *branch-filters
      - docker/publish:
          name: publish-clubs-frontend
          requires:
            - react-tools/check
          path: frontend
          cache_from: "pennlabs/penn-clubs-frontend:latest"
          image: "pennlabs/penn-clubs-frontend"
          tag: "${CIRCLE_SHA1},latest"
          context: docker-publish
          <<: *branch-filters
      - docker/publish:
          name: publish-hub-backend
          requires:
            - django-tools/check
          path: backend
          cache_from: "pennlabs/first-year-hub-backend:latest"
          image: "pennlabs/first-year-hub-backend"
          tag: "${CIRCLE_SHA1},latest"
          context: docker-publish
          <<: *branch-filters
      - docker/publish:
          name: publish-hub-frontend
          requires:
            - react-tools/check
          path: frontend
          extra_build_args: "--build-arg NEXT_PUBLIC_SITE_NAME=fyh"
          cache_from: "pennlabs/first-year-hub-frontend:latest"
          image: "pennlabs/first-year-hub-frontend"
          tag: "${CIRCLE_SHA1},latest"
          context: docker-publish
          <<: *branch-filters
      - helm-tools/deploy:
          requires:
            - publish-clubs-backend
            - publish-clubs-frontend
            - publish-hub-backend
            - publish-hub-frontend
          context: k8s-deploy
          <<: *branch-filters
