deploy_version: 0.1.22
image_tag: latest

applications:
  - name: redis
    image: redis
    tag: "6.0"
    port: 6379
  - name: django-asgi
    image: pennlabs/penn-clubs-backend
    secret: penn-clubs
    cmd: ["/usr/local/bin/asgi-run"]
    replicas: 2
    ingress:
      hosts:
        - host: pennclubs.com
          paths: ["/api/ws"]
    extraEnv:
      - name: DOMAIN
        value: pennclubs.com
      - name: DJANGO_SETTINGS_MODULE
        value: pennclubs.settings.production
      - name: REDIS_HOST
        value: penn-clubs-redis
  - name: django-wgsi
    image: pennlabs/penn-clubs-backend
    secret: penn-clubs
    replicas: 3
    ingress:
      hosts:
        - host: pennclubs.com
          paths: ["/api"]
    extraEnv:
      - name: DOMAIN
        value: pennclubs.com
      - name: DJANGO_SETTINGS_MODULE
        value: pennclubs.settings.production
      - name: REDIS_HOST
        value: penn-clubs-redis
  - name: react
    image: pennlabs/penn-clubs-frontend
    replicas: 2
    ingress:
      hosts:
        - host: pennclubs.com
          paths: ["/"]
    extraEnv:
      - name: PORT
        value: 80
      - name: DOMAIN
        value: pennclubs.com
  - name: hub-redis
    image: redis
    tag: "6.0"
    port: 6379
  - name: hub-django-asgi
    image: pennlabs/penn-clubs-backend
    secret: first-year-hub
    cmd: ["/usr/local/bin/asgi-run"]
    replicas: 2
    ingress:
      hosts:
        - host: hub.provost.upenn.edu
          paths: ["/api/ws"]
    extraEnv:
      - name: DOMAIN
        value: hub.provost.upenn.edu
      - name: NEXT_PUBLIC_SITE_NAME
        value: fyh
      - name: DJANGO_SETTINGS_MODULE
        value: pennclubs.settings.production
      - name: REDIS_HOST
        value: penn-clubs-hub-redis
  - name: hub-django-wgsi
    image: pennlabs/penn-clubs-backend
    secret: first-year-hub
    replicas: 3
    ingress:
      hosts:
        - host: hub.provost.upenn.edu
          paths: ["/api"]
    extraEnv:
      - name: DOMAIN
        value: hub.provost.upenn.edu
      - name: NEXT_PUBLIC_SITE_NAME
        value: fyh
      - name: DJANGO_SETTINGS_MODULE
        value: pennclubs.settings.production
      - name: REDIS_HOST
        value: penn-clubs-hub-redis
  - name: hub-react
    image: pennlabs/penn-clubs-frontend
    replicas: 2
    ingress:
      hosts:
        - host: hub.provost.upenn.edu
          paths: ["/"]
    extraEnv:
      - name: PORT
        value: 80
      - name: DOMAIN
        value: hub.provost.upenn.edu
      - name: NEXT_PUBLIC_SITE_NAME
        value: fyh

cronjobs:
  - name: rank-clubs
    schedule: "0 8 * * *"
    image: pennlabs/penn-clubs-backend
    secret: penn-clubs
    cmd: ["python", "manage.py", "rank"]
  - name: daily-notifications
    schedule: "0 13 * * *"
    image: pennlabs/penn-clubs-backend
    secret: penn-clubs
    cmd: ["python", "manage.py", "daily_notifications"]
  - name: hub-daily-notifications
    schedule: "0 13 * * *"
    image: pennlabs/penn-clubs-backend
    secret: first-year-hub
    cmd: ["python", "manage.py", "daily_notifications"]
  - name: calendar-import
    schedule: "0 12 * * *"
    image: pennlabs/penn-clubs-backend
    secret: penn-clubs
    cmd: ["python", "manage.py", "import_calendar_events"]
  - name: hub-calendar-import
    schedule: "0 12 * * *"
    image: pennlabs/penn-clubs-backend
    secret: first-year-hub
    cmd: ["python", "manage.py", "import_calendar_events"]
