deploy_version: 0.1.11
image_tag: latest

applications:
  - name: django
    image: pennlabs/pennclubs-backend
    secret: pennclubs
    ingress:
      hosts:
        - host: pennclubs.com
          paths: ["/api"]
    extraEnv:
      - name: DOMAIN
        value: pennclubs.com
      - name: DJANGO_SETTINGS_MODULE
        value: pennclubs.settings.production
  - name: react
    image: pennlabs/pennclubs-frontend
    secret: pennclubs
    ingress:
      hosts:
        - host: pennclubs.com
          paths: ["/"]
    extraEnv:
      - name: PORT
        value: 80
      - name: DOMAIN
        value: pennclubs.com
