apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-svc
{{ if .Values.staging }}
  namespace: staging
{{- end }}
spec:
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: 80
  selector:
    name: {{ .Release.Name }}-backend